import { Furniture } from './types'

export const FURNITURE_CATALOG: Furniture[] = [
  {
    id: '1',
    name: 'Modern Gray Sofa',
    category: 'Seating',
    style: 'Contemporary',
    dimensions: { width: 200, length: 90, height: 85 },
    price: 45000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Perfect fit for contemporary spaces with excellent comfort',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop',
  },
  {
    id: '2',
    name: 'Solid Wood Coffee Table',
    category: 'Tables',
    style: 'Minimalist',
    dimensions: { width: 100, length: 60, height: 45 },
    price: 12000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Complements modern aesthetics with natural wood warmth',
    imageUrl: 'https://images.unsplash.com/photo-1532159553688-03d3c6be5700?w=400&h=300&fit=crop',
  },
  {
    id: '3',
    name: 'Floating Wall Shelves Set',
    category: 'Storage',
    style: 'Scandinavian',
    dimensions: { width: 120, length: 20, height: 15 },
    price: 8000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Maximizes vertical space and adds architectural interest',
    imageUrl: 'https://images.unsplash.com/photo-1595521624059-46d7b7b56f11?w=400&h=300&fit=crop',
  },
  {
    id: '4',
    name: 'Mid-Century Dining Table',
    category: 'Tables',
    style: 'Mid-Century',
    dimensions: { width: 150, length: 80, height: 75 },
    price: 28000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Classic lines work well with retro and contemporary styles',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400&h=300&fit=crop',
  },
  {
    id: '5',
    name: 'Ergonomic Office Chair',
    category: 'Seating',
    style: 'Contemporary',
    dimensions: { width: 60, length: 65, height: 110 },
    price: 18000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Provides comfort and professional appearance for work areas',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=400&h=300&fit=crop',
  },
  {
    id: '6',
    name: 'Pendant Light Trio',
    category: 'Lighting',
    style: 'Contemporary',
    dimensions: { width: 250, length: 20, height: 30 },
    price: 15000,
    stockStatus: 'Limited',
    reasonForSelection: 'Creates ambient lighting and adds visual depth',
    imageUrl: 'https://images.unsplash.com/photo-1565182999555-022adf3cf3f0?w=400&h=300&fit=crop',
  },
  {
    id: '7',
    name: 'Area Rug 200x300cm',
    category: 'Accessories',
    style: 'Scandinavian',
    dimensions: { width: 200, length: 300, height: 1 },
    price: 22000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Defines space and adds warmth to the living area',
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
  },
  {
    id: '8',
    name: 'Bookshelf Unit',
    category: 'Storage',
    style: 'Minimalist',
    dimensions: { width: 160, length: 35, height: 180 },
    price: 32000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Provides ample storage while maintaining clean aesthetics',
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
  },
  {
    id: '9',
    name: 'Accent Chair Velvet',
    category: 'Seating',
    style: 'Contemporary',
    dimensions: { width: 75, length: 80, height: 85 },
    price: 16000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Adds luxury and visual interest to the space',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop',
  },
  {
    id: '10',
    name: 'Wall Art Set',
    category: 'Accessories',
    style: 'Contemporary',
    dimensions: { width: 100, length: 2, height: 120 },
    price: 5000,
    stockStatus: 'In Stock',
    reasonForSelection: 'Enhances visual interest and personalizes the space',
    imageUrl: 'https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=400&h=300&fit=crop',
  },
]

export const ROOM_TYPES = ['Living Room', 'Bedroom', 'Home Office', 'Dining Room', 'Kitchen']
export const INTERIOR_STYLES = ['Modern', 'Minimalist', 'Scandinavian', 'Mid-Century', 'Contemporary']
export const MUST_HAVE_CATEGORIES = ['Sofa', 'Bed', 'Desk', 'Dining Table', 'Coffee Table', 'Shelves', 'Lamp', 'Rug']
